/**
 * parenting Web Dashboard — index of pure helpers and entry points.
 */

export {
	DEFAULT_LOCALE,
	type I18nContextValue,
	I18nProvider,
	LanguageSwitcher,
	LOCALE_LABELS,
	LOCALES,
	type Locale,
	MESSAGES,
	type MessageKey,
	readStoredLocale,
	translate,
	useI18n,
	writeStoredLocale,
} from "./i18n.js";
export {
	appBodyGridStyle,
	appContainerInlineStyle,
	type BreakpointName,
	centeredContainerStyle,
	headerInlineStyle,
	LAYOUT,
	resolveBreakpoint,
	responsiveColumns,
} from "./layout.js";
export { IndexedDbMemoryLayer } from "./memory-indexeddb.js";
export { type MemoryLayerLike, WebMemoryLayer } from "./memory-web.js";
export type { WebOrchestrator } from "./orchestrator.js";
export {
	createWebOrchestrator,
	createWebOrchestratorWithPersistence,
} from "./orchestrator.js";
export {
	applyTheme,
	DEFAULT_THEME,
	nextTheme,
	readStoredTheme,
	THEME_NAMES,
	THEME_VARS,
	THEMES,
	type ThemeContextValue,
	type ThemeMeta,
	type ThemeName,
	ThemeProvider,
	ThemeSwitcher,
	useTheme,
	writeStoredTheme,
} from "./theme.js";
export { WEB_VERSION } from "./version.js";
export type { Action, AppState, ChatMessage, IRNode } from "./view.js";
export {
	buildSetConvergenceAction,
	createParentingApp,
	createParentingAppWithPersistence,
	defaultChild,
	dispatchAsk,
	initialState,
	listWebAgentIds,
	newMessageId,
	recordMessageFeedback,
	reducer,
	renderView,
	runAsk,
} from "./view.js";
export type {
	E2eMainPathReport,
	E2eMainPathStep,
	WebConvergenceSnapshot,
	WebLlmCompletion,
	WebLlmProvider,
	WebLlmRegistry,
} from "./web-convergence.js";
export {
	buildE2eMainPathReport,
	buildRealLlmProviderChain,
	buildWebConvergenceSnapshot,
	createAnthropicCompatibleProvider,
	createMinimaxM3Provider,
	createOpenAICompatibleProvider,
	createRuleFallbackProvider,
	createWebLlmProvider,
	createXiaomiMiMoProvider,
	readEnv,
	registerWebLlmProviders,
	type RemoteLlmProviderOptions,
	type LlmFetch,
	type LlmApiFormat,
} from "./web-convergence.js";
export { loadDotenv, resolveEnvPath } from "./dotenv.js";
export type {
	DevelopmentDomain,
	DevelopmentGraphEdge,
	DevelopmentGraphNode,
	DevelopmentObservation,
	DevelopmentTrend,
	IterationDirection,
	IterationDirectionId,
	IterationSuiteSnapshot,
	LongitudinalDevelopmentInsightGraph,
	LongitudinalDevelopmentInsightGraphInput,
	MultiChildTrendPack,
	OfflineCoachMode,
	ParentingCompletionAction,
	ParentingCompletionActionId,
	ParentingCompletionPack,
	ParentingCompletionPackInput,
	ParentingScenario,
	ParentStressSnapshot,
	ProviderConfigSnapshot,
	ReleaseGatePlan,
	ReleaseGateStep,
	SevenDirectionClosureAction,
	SevenDirectionClosureActionId,
	SevenDirectionClosureCenter,
	SevenDirectionClosureCenterInput,
	ActionPlanBoard,
	AgentCollaborationDag,
	AgentDagEdge,
	AgentDagNode,
	AgentDagNodeKind,
	GuidedIntakeStep,
	GuidedIntakeStepId,
	GuidedIntakeWizard,
	WebInteractionDirection,
	WebInteractionDirectionId,
	WebInteractionWorkbench,
	WeeklyCoachingDay,
	WeeklyCoachingStressInput,
	WeeklyCoachingStressPlan,
} from "./web-iteration-suite.js";
export {
	buildAcceptanceEvidence,
	buildActionPlanGenerator,
	buildActionPlanBoard,
	applyActionPlanToggle,
	applyActionPlanNote,
	buildAgentCollaborationDag,
	buildGuidedIntakeWizard,
	buildAgentCollaborationExplanation,
	buildAllDirectionsProductHub,
	buildBilingualKnowledgeBase,
	buildClosedLoopEvidenceLedger,
	buildDeliveryReportExport,
	buildE2eDrill,
	buildFamilyProfileCenter,
	buildFamilyTimelineFilters,
	buildFeedbackRepairLoop,
	buildIterationSuite,
	buildLlmProviderConfigForm,
	buildLongitudinalDevelopmentInsightGraph,
	buildMedicalSafetyEscalation,
	buildMemoryTimeline,
	buildMultiChildContextSwitcher,
	buildOfflineSyncOperations,
	buildParentingClosedLoopPlan,
	buildParentingCompletionPack,
	buildParentingExecutionCenter,
	buildParentProgressDashboard,
	buildProviderConfigSnapshot,
	buildProviderModeOptions,
	buildReleaseGatePlan,
	buildRuntimeDashboardSnapshot,
	buildSafetyFirstMode,
	buildScenarioPack,
	buildScenarioTemplateLibrary,
	buildScenarioWorkflow,
	buildSevenDirectionClosureCenter,
	buildSyncConflictResolution,
	buildSyncQueueActions,
	buildSyncQueueOperationPlan,
	buildWebInteractionWorkbench,
	serializeWorkbenchState,
	deserializeWorkbenchState,
	buildAgentWeightHints,
	buildDagAgentShortcut,
	buildAgentNodeActions,
	buildSelectedAgentHint,
	buildWeeklyCoachingStressPlan,
	buildOrchestratorHintBoosts,
} from "./web-iteration-suite.js";
export type {
	WorkbenchPersistedState,
	AgentWeightHints,
	DagAgentShortcut,
} from "./web-iteration-suite.js";
export { WorkbenchPanel, type WorkbenchPanelProps } from "./workbench-panel.js";
